/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair(props) {
    const { nodes, materials } = useGLTF('./models/chair.glb')
    return (
        <group {...props} dispose={null}  >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled008.geometry}
                material={materials['palette.028']}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    )
}

// useGLTF.preload('/chair.glb')
