/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ChristmassTree(props) {
    const { nodes, materials } = useGLTF('./models/christmassTree.glb')
    return (
        <group {...props} dispose={null}>
            <group name="christmas_tree" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    name="christmas_tree_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.christmas_tree_1.geometry}
                    material={materials.holiday}
                />
                <mesh
                    name="christmas_tree_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.christmas_tree_2.geometry}
                    material={materials.holiday_glow}
                />
            </group>
            <mesh
                name="christmas_tree_base"
                castShadow
                receiveShadow
                geometry={nodes.christmas_tree_base.geometry}
                material={materials.holiday}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <group name="christmas_tree_decorated" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    name="christmas_tree_decorated_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.christmas_tree_decorated_1.geometry}
                    material={materials.holiday}
                />
                <mesh
                    name="christmas_tree_decorated_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.christmas_tree_decorated_2.geometry}
                    material={materials.holiday_glow}
                />
            </group>
        </group>
    )
}

// useGLTF.preload('/christmassTree.glb')
