/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Suspense } from "react";
import { useGLTF } from "@react-three/drei";
import { motion } from "framer-motion";

import { Cupboard } from "./Cupboard";
import { Cupboard2 } from "./Cupboard2";
import { Chair } from "./Chair";
import { Lamp } from "./Lamp";
import { Plant } from "./Plant";
import { PictureFrame } from "./PictureFrame";
import { SmallCupboard } from "./SmallCupboard";
import { withSceneFeatures } from "./WithSceneFeatures";
import { Computer } from "./Computer";
import { Table } from "./Table";
import { ChristmassTree } from "./ChristmassTree";
import { Move } from "lucide-react";


export function EmptyRoom(props) {
    const { nodes, materials } = useGLTF("./models/Empty_Room.glb");

    // 🪑 Interactive chair
    const BouncingChair = withSceneFeatures(Chair, {
        animate: false,
        idleType: "tilt",
        hoverEffect: true,
        clickEffect: true,
    });

    // 🪴 Gentle idle animations for decor/furniture
    const MoveLamp = withSceneFeatures(Lamp, { animate: false, idleType: "tilt", amplitude: 0.02, speed: 0.5 });
    const MoveCupboard1 = withSceneFeatures(Cupboard, { animate: false });
    const MoveCupboard2 = withSceneFeatures(Cupboard2, { animate: false });
    const MovePlant = withSceneFeatures(Plant, { animate: false, idleType: "tilt", amplitude: 0.03, speed: 1 });
    const MovePictureFrame = withSceneFeatures(PictureFrame, { animate: false, idleType: "tilt", amplitude: 0.02, speed: 0.7 });
    const MoveSmallCupboard = withSceneFeatures(SmallCupboard, { animate: false });

    const MoveChristmassTree = withSceneFeatures(ChristmassTree, { animate: true, idleType: "bounce", amplitude: 0.02, speed: 1 });

    const objects = [
        { component: MoveLamp, key: "lamp" },
        { component: MoveCupboard1, key: "cupboard1" },
        { component: MoveCupboard2, key: "cupboard2" },
        { component: MovePlant, key: "plant" },
        { component: MovePictureFrame, key: "frame" },
        { component: MoveSmallCupboard, key: "smallCupboard" },
        { component: MoveChristmassTree, key: "christmassTree", props: { scale: 0.25, position: [0.7, 0.13, 0.2] } },
    ];
    return (
        <motion.group
            {...props}
            dispose={null}
            initial={{ opacity: 0, rotation: [0, -Math.PI / 6, 0], scale: 0.9 }}
            animate={{ opacity: 1, rotation: [0, 0, 0], scale: 1 }}
            transition={{
                duration: 2.5,
                ease: [0.16, 1, 0.3, 1],
                delay: 0.3,
            }}
        >
            {/* === Invisible floor (for shadows) === */}
            <mesh visible={true} position={[0, -0.19, 0]}>
                <boxGeometry args={[5, 0.2, 5]} />
                <meshStandardMaterial transparent opacity={0} />
            </mesh>

            {/* === Room structure === */}
            {[
                "Untitled",
                "Untitled001",
                "Untitled002",
                "Untitled005",
                "Untitled011",
                "Untitled012",
                "Untitled013",
                "Untitled014",
                "Untitled015",
            ].map((key) => (
                <mesh
                    key={key}
                    castShadow
                    receiveShadow
                    geometry={nodes[key]?.geometry}
                    material={materials["palette.002"]}
                    rotation={[Math.PI / 2, 0, 0]}
                />
            ))}

            {/* === Furniture & decor === */}

            {objects.map(({ component: Component, key }, index) => (
                <Suspense key={key} fallback={null}>
                    <motion.group
                        initial={{ y: 2, opacity: 0, rotateY: Math.PI / 4 }}
                        animate={{ y: 0, opacity: 1, rotateY: 0 }}
                        transition={{ duration: 1, delay: index * 0.3, ease: "easeOut" }}
                    >
                        <Component {...(objects[index]?.props || {})} />
                    </motion.group>
                </Suspense>
            ))}

            <Suspense fallback={null}>
                <BouncingChair position={[-0.7, 0, 0.24]} rotation={[0, Math.PI / 1, 0]} />
            </Suspense>
            <Suspense fallback={null}>

                <Computer scale={0.6} position={[-0.5, 0.45, 0.15]} rotation={[0, Math.PI / 2, 0]} />
                <Table scale={0.25} position={[-0.67, 0, 0.1]} rotation={[0, Math.PI / 2, 0]} />
            </Suspense>
        </motion.group >
    );
}

useGLTF.preload("./models/Empty_Room.glb");
