/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF } from "@react-three/drei";

export function Lamp(props) {
    const { nodes, materials } = useGLTF("./models/lamp.glb");
    const lightRef = useRef();
    const [isDark, setIsDark] = useState(false);

    // 🌗 Check theme on mount + listen for changes
    useEffect(() => {
        const updateTheme = () => {
            const theme = localStorage.getItem("vite-ui-theme");
            const htmlDark = document.documentElement.classList.contains("dark");
            setIsDark(theme === "dark" || htmlDark);
        };

        updateTheme(); // initial
        const observer = new MutationObserver(updateTheme);
        observer.observe(document.documentElement, {
            attributes: true,
            attributeFilter: ["class"],
        });

        window.addEventListener("storage", updateTheme);
        return () => {
            window.removeEventListener("storage", updateTheme);
            observer.disconnect();
        };
    }, []);

    return (
        <group {...props} dispose={null}>
            {/* Lamp body */}
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled009.geometry}
                material={materials["palette.029"]}
                rotation={[Math.PI / 2, 0, 0]}
            />

            {/* Lamp shade */}
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled010.geometry}
                material={materials["palette.029"]}
                rotation={[Math.PI / 2, 0, 0]}
            />

            {/* 💡 Light only visible in dark mode */}
            {isDark && (
                <>
                    <pointLight
                        ref={lightRef}
                        position={[-0.63, 0.5, -0.3]}
                        intensity={0.6}
                        distance={5}
                        decay={2}
                        color={"#fff7e6"}
                        castShadow
                        shadow-mapSize-width={1024}
                        shadow-mapSize-height={1024}
                    />

                    {/* Glowing bulb */}
                    <mesh position={[-0.7, 0.5, -0.37]}>
                        <sphereGeometry args={[0.03, 16, 16]} />
                        <meshStandardMaterial
                            emissive={"#fff7e6"}
                            emissiveIntensity={3}
                            color={"#fff7e6"}
                        />
                    </mesh>
                </>
            )}
        </group>
    );
}
