// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function PictureFrame(props) {
//     const { nodes, materials } = useGLTF('./models/picture_frame.glb')
//     return (
//         <group {...props} dispose={null}>
//             <mesh
//                 castShadow
//                 receiveShadow
//                 geometry={nodes.Untitled004.geometry}
//                 material={materials['palette.024']}
//                 rotation={[Math.PI / 2, 0, 0]}
//                 emissive={"#00aaff"}             // light blue glow
//                 emissiveIntensity={2}
//             />
//         </group>
//     )
// }

// // useGLTF.preload('/picture_frame.glb')


import React, { useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

export function PictureFrame(props) {
    const { nodes, materials } = useGLTF('./models/picture_frame.glb');

    // 🧠 Create a glowing clone of the material
    const glowMaterial = useMemo(() => {
        const mat = materials['palette.024'].clone();
        mat.emissive = new THREE.Color('#0f1aff');  // color of the glow
        mat.emissiveIntensity = 2;                  // brightness
        mat.emissiveMap = null;                     // optional
        return mat;
    }, [materials]);

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled004.geometry}
                material={glowMaterial}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    );
}
