/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plant(props) {
    const { nodes, materials } = useGLTF('./models/plant.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled007.geometry}
                material={materials['palette.027']}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    )
}

// useGLTF.preload('/plant.glb')
