/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Room2(props) {
    const { nodes, materials } = useGLTF('./models/Room_Model_v02_compressed.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled001.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cupboard.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled002.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled003.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled004.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled005.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled006.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled007.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled008.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled010.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, -1.256]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled011.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled012.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled013.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled014.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled015.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled016.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled017.geometry}
                material={materials['palette.002']}
                position={[-1.902, 0, 0.243]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.cabinet_small_decorated_Cube048.geometry}
                material={materials['furniture_texture.011']}
                position={[-1.805, 0.087, 0.837]}
                rotation={[Math.PI / 2, 0, -1.655]}
                scale={0.329}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.cactus_small_B_Cylinder002.geometry}
                material={materials['furniture_texture.011']}
                position={[-0.868, 0.572, -0.83]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.329}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.rug_rectangle_stripes_A_Cube022.geometry}
                material={materials['furniture_texture.011']}
                position={[-0.388, 0.093, -0.707]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.169}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.table_medium_long_Cube004.geometry}
                material={materials['furniture_texture.011']}
                position={[-1.718, 0.097, 0.122]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.24}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled009.geometry}
                material={materials['palette.021']}
                position={[-1.881, 0.345, -0.157]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.046}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled018.geometry}
                material={materials['palette.022']}
                position={[-1.908, 0.325, 0.408]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.039}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Monitor_1.geometry}
                material={materials['Monitor_1_Material.001']}
                position={[-1.807, 0.339, 0.136]}
                rotation={[0, 1.454, 0]}
                scale={[0.449, 0.451, 0.31]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled019.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled020.geometry}
                material={materials['palette.002']}
                position={[0.884, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled021.geometry}
                material={materials['palette.002']}
                position={[0.984, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled022.geometry}
                material={materials['palette.002']}
                position={[0.984, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.wreath.geometry}
                material={materials['holiday.109']}
                position={[-0.462, 0.702, -1.13]}
                rotation={[Math.PI / 2, 0, 3.031]}
                scale={0.192}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Untitled023.geometry}
                material={materials['palette.002']}
                position={[0.349, -0.021, -2.028]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
            />
        </group>
    )
}

// useGLTF.preload('/Room_Model_v02_compressed.glb')
