/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Suspense, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Cupboard } from './Cupboard'
import { Cupboard2 } from './Cupboard2'

export function Room(props) {
    const { nodes, materials } = useGLTF('./models/Room_v03.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Ground_slab_1.geometry}
                material={materials['palette.002']}
                position={[-1.116, 0, -0.3]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            {/* <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cupboard_1.geometry}
                material={materials['palette.003']}
                position={[-1.116, 0, -0.3]}
                rotation={[Math.PI / 2, 0, 0]}
            /> */}

            <Suspense >
                <Cupboard
                    castShadow
                    receiveShadow
                    geometry={nodes.Cupboard_1.geometry}
                    material={materials['palette.003']}
                    position={[-1.1, 0, -0.3]}
                />
            </Suspense>

            <Cupboard2

                castShadow
                receiveShadow
                geometry={nodes.Cupboard_1.geometry}
                material={materials['palette.003']}
                position={[-1.116, 0, -0.3]}
            />

            {/* <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cupboard_2.geometry}
                material={materials['palette.004']}
                position={[-1.116, 0, -0.3]}
                rotation={[Math.PI / 2, 0, 0]}
            /> */}
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Window_Exterior.geometry}
                material={materials['palette.005']}
                position={[-1.116, 0, -0.139]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Wall_Exterrior_2.geometry}
                material={materials['palette.006']}
                position={[-1.116, 0, -0.3]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Wall_Exterrior_1.geometry}
                material={materials['palette.007']}
                position={[-1.116, 0, -0.3]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Wall_Interrior_1.geometry}
                material={materials['palette.008']}
                position={[-1.116, 0, -0.3]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Window_Midsection.geometry}
                material={materials['palette.009']}
                position={[-1.116, 0, -0.3]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Lamp.geometry}
                material={materials['palette.010']}
                position={[-1.116, 0, -0.194]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Lamp_table.geometry}
                material={materials['palette.011']}
                position={[-1.116, 0, -0.194]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plant.geometry}
                material={materials['palette.013']}
                position={[-1.116, 0, -1.519]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Wall_Picture_Frame.geometry}
                material={materials['palette.014']}
                position={[-1.116, 0, -0.3]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Window_Interrior.geometry}
                material={materials['palette.015']}
                position={[-1.116, 0, -0.1]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Picture_Frame.geometry}
                material={materials['palette.016']}
                position={[-1.116, 0, -0.3]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Drawer.geometry}
                material={materials['palette.017']}
                position={[-1.116, 0, -0.3]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Door_1.geometry}
                material={materials['palette.018']}
                position={[-1.116, 0, -0.3]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Wall_Interrior_2.geometry}
                material={materials['palette.019']}
                position={[-1.116, 0, -0.3]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Chair.geometry}
                material={materials['palette.020']}
                position={[-1.902, 0, 0.121]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.cactus_small_B_Cylinder002.geometry}
                material={materials['furniture_texture.015']}
                position={[-0.868, 0.572, -1.13]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.329}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.rug_rectangle_stripes_A_Cube022.geometry}
                material={materials['furniture_texture.041']}
                position={[-0.388, 0.093, -1.007]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.169}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.table_medium_long_Cube004.geometry}
                material={materials['furniture_texture.055']}
                position={[-1.718, 0.097, 0]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.24}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Robo_2.geometry}
                material={materials['palette.021']}
                position={[-1.881, 0.345, -0.279]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.046}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Robo_1.geometry}
                material={materials['palette.022']}
                position={[-1.908, 0.325, 0.286]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.039}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Monitor_1.geometry}
                material={materials['Monitor_1_Material.001']}
                position={[-1.807, 0.339, 0]}
                rotation={[0, 1.454, 0]}
                scale={[0.449, 0.451, 0.31]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.wreath.geometry}
                material={materials['holiday.109']}
                position={[-0.388, 0.702, -1.429]}
                rotation={[Math.PI / 2, 0, 3.031]}
                scale={0.192}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Door_Exterior.geometry}
                material={materials['palette.028']}
                position={[0.349, -0.021, -2.328]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.food_burger_Cylinder074.geometry}
                material={materials.restaurant}
                position={[-1.7, 0.318, -0.275]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.147}
            />

        </group>
    )
}
