/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Table(props) {
    const { nodes, materials } = useGLTF('./models/table.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                name="table_medium_Cube003"
                castShadow
                receiveShadow
                geometry={nodes.table_medium_Cube003.geometry}
                material={materials['furniture_texture.001']}
                position={[-0.063, 0.208, 0.229]}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    )
}

useGLTF.preload('/table.glb')
